//
// Generated by JTB 1.3.2
//

package inliner.syntaxtree;

/**
 * Grammar production:
 * f0 -> ArrayType()
 *       | BooleanType()
 *       | IntegerType()
 *       | Identifier()
 */
public class Type implements Node {
   public NodeChoice f0;

   public Type(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(inliner.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(inliner.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(inliner.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(inliner.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

