//
// Generated by JTB 1.3.2
//

package nano.syntaxtree;

/**
 * Grammar production:
 * f0 -> ClassDeclaration()
 *       | ClassExtendsDeclaration()
 */
public class TypeDeclaration implements Node {
   public NodeChoice f0;

   public TypeDeclaration(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(nano.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(nano.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(nano.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(nano.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

